#!/bin/bash

if [ -n "$1" ]; then ssh="ssh $1 -t"; fi

socket=dev
session=$($ssh tmux -L $socket ls 2>&1 | head -n1 | \
	grep -v failed | awk -F ':' '{print $1}')

if [ -n "$session" ]; then attach=" attach"; fi

$ssh tmux -L $socket$attach
