#!/bin/bash

man="\
USAGE
	$(basename $0) [HOST:][docs|flash] [OPTIONS]

OPTIONS

	-n dry run
	-r restore instead of backup
	-h this help
"

function sync() {
	from=$1; to=$2; n=$3

	mkdir -p $to
	rsync -av --delete $n $from $to
}

function restore() {
	from=$1; to=$2; n=$3
	sync $to $from $n
}

flash=$FLASH_ROOT/flash
home=$HOME

IFS=$':'; target=($1); IFS=$' '

if [ -z "${target[1]}" ]; then
	name="${target[0]}"
else
	host="${target[0]}:"
	name="${target[1]}"
fi

command=sync

for ((i=0;++i<=$#;)); do
	case ${@:$i:1} in
		-n) n=-n ;;
		-h) help=help ;;
		-r) command=restore ;;
	esac
done

if [ -n "$help" ]; then echo "$man"; exit 0; fi

if [ -z "$FLASH_ROOT" ]; then echo "\$FLASH_ROOT is empty."; exit 1; fi
if [ ! -d "$FLASH_ROOT" ]; then echo "$FLASH_ROOT is not found."; exit 1; fi

case "$name" in
	docs) $command $host$home/Documents/ $flash/docs/ $n ;;
	flash) $command $flash/ $host$home/flash/ $n ;;
	*) $command $flash/ $home/flash/ $n ;;
esac
