#!/bin/bash

man="\
USAGE
	$(basename $0) [ssh|docs] [OPTIONS]

OPTIONS

	-n dry run
	-r restore instead of backup
	-h this help
"

function sync() {
	from=$1; to=$2; n=$3

	mkdir -p $to
	rsync -av --delete $n $from $to
}

function restore() {
	from=$1; to=$2; n=$3
	sync $to $from $n
}

target=$1
command=sync

for ((i=0;++i<=$#;)); do
	case ${@:$i:1} in
		-n) n=-n ;;
		-h) help=help ;;
		-r) command=restore ;;
	esac
done

if [ -z "$FLASH_ROOT" ]; then echo "\$FLASH_ROOT is empty."; exit 1; fi
if [ -n "$help" ]; then echo "$man"; exit 0; fi

case "$target" in
	ssh) $command $HOME/.ssh/ $FLASH_ROOT/flash/ssh/ $n ;;
	git) $command dogit:/home/git/ $FLASH_ROOT/flash/git/ $n ;;
	docs) $command $HOME/Documents/ $FLASH_ROOT/flash/docs/ $n ;;
	*) $command $FLASH_ROOT/flash/ $HOME/flash/ $n ;;
esac
