#!/bin/bash

target=$1
options=${@:2}

function sync() {
	from=$1; to=$2; options=${@:3}

	if [ ! -d "$from" ]; then echo "$from is not found."; exit 1; fi

	mkdir -p $to
	rsync -av $options $from $to
}

if [ -z "$target" ]; then echo "$usage"; exit 1; fi
if [ -z "$FLASH_ROOT" ]; then echo "\$FLASH_ROOT is empty."; exit 1; fi

case "$target" in
	ssh) sync $HOME/.ssh/ $FLASH_ROOT/flash/ssh/ --delete $options ;;
	docs) sync $HOME/Documents/ $FLASH_ROOT/flash/docs/ --delete $options ;;

	*) sync $FLASH_ROOT/flash/ $HOME/flash/ --delete $options ;;
esac
