#!/bin/bash

man="
USAGE
	snapshot [OPTIONS]

OPTIONS

	--root <backup_root>
		Root directory for the snapshot.

	--path <backup_path>
		Relative path (will be appended to backup_root) where snapshot
		will be located.

	--overwrite
		Will overwrite existing snapshot if any.
		Without this option creates another snapshot adding current
		date and time as a suffix.

	--exceptions <file_path>
		Specifies file with list of exceptions should not be added to snapshot.

	--help
		This help message.
"

target=${PWD##*/}
extension=tar.bz2
date_format="+%Y%m%d_%H%M%S"

for ((i=0;++i<=$#;))
do
	case ${@:$i:1} in
		--root) root=${@:$i+1:1} ;;
		--path) path=${@:$i+1:1} ;;
		--exceptions) exceptions=${@:$i+1:1} ;;
		--overwrite) filename=$target.$extension ;;
		--help) help=help ;;
	esac
done

if [ -n "$help" ]; then echo "$man"; exit 0; fi
if [ -n "$root" ] && [ ! -d "$root" ]; then echo "$root not found."; exit 1; fi

if [ -z "$filename" ]; then
	filename=$target\_$(date $date_format).$extension
fi

if [ -n "$exceptions" ]; then
	if [ ! -f "$exceptions" ]; then echo "$exceptions not found."; exit 1; fi
	exceptions="-X $exceptions"
fi

cd ../
tar vjcf $filename $exceptions $target

if [ -n "$root" ]; then
	mkdir -p $root/$path/$target
	mv $filename $root/$path/$target
fi
