#!/bin/bash

usage="usage: $(basename $0) <socket> [host]"

socket=$1
host=$2

if [ -z "$socket" ]; then echo "$usage"; exit 0; fi
if [ -n "$host" ]; then ssh="ssh $host -t"; fi

session=$($ssh tmux -L $socket ls | grep -v failed | cut -d: -f1)
if [ -n "$session" ]; then attach=" attach"; fi

$ssh tmux -L $socket$attach
